### PR TITLE
Shailendra

### PR DESCRIPTION
**Pull request by SPratapIND**
update #87

### CODE REVIEW

**Review by MiRoVaGo — CHANGES_REQUESTED** [review]
There are no visible changes in the resulting figure

**Comment by imarkonis** [comment]
The generated file in Shailendra's paper has thick border. The generated file in our original script hasn't. Can we fix this?

**Comment by MiRoVaGo** [comment]
We cannot unless we re-project the data.
Shailendra did it in the same fashion of the example you shared previously (warping latlon so that it looks like robinson in the regular space)

**Comment by imarkonis** [comment]
So let's reproject them and see how they look like. When rgdal is retired we will figure out another solution. Who is going to do the re-projection?

**Comment by imarkonis** [comment]
We stick to the older version. Made some work around myself.

**Pull request closed without merging**
